# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "helpers"
pin "config"
pin "jquery"
pin "popper"
pin "bootstrap"
pin "perfect-scrollbar"
pin "menu"
pin "main"
