# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day
daily_reminder_monthly_billing_duedate_report:
  class: MonthlyBillingDuedateReminderJob
  queue: default
  schedule: "0 0 * * *" #every 12 AM

daily_reminder_charge_penalty_report:
  class: ChargePenaltyNotificationJob
  queue: default
  schedule: "0 0 * * *" #every 12 AM
